name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        npm install
        npm run build
        cd dist
        echo vuejs-demo.congnguyen.dev > CNAME
        git init
        git add -A
        git commit -m "hello"
        git push -f https://github.com/nguyenvancongdev/vuejs-demo.git master:gh-pages
        